### ISSUE TITLE
Unable to instantiate service androidx.browser.trusted.TrustedWebActivityService

### ISSUE THREAD

**Issue by rod-stuchi** [GoogleChromeLabs/svgomg-twa#101]
Hi

I'm have trouble in a cold start of the App

![screenshot 2020-04-09T13 16 40](https://user-images.githubusercontent.com/19471811/78916955-9991aa00-7a64-11ea-9aae-ce9983e8f70e.png)

```
04-09 13:16:10.704  4651  4651 E AndroidRuntime: FATAL EXCEPTION: main
04-09 13:16:10.704  4651  4651 E AndroidRuntime: Process: br.com.dialog.unimed, PID: 4651
04-09 13:16:10.704  4651  4651 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate service androidx.browser.trusted.TrustedWebActivityService: java.lang.InstantiationException: java.lang.Class<androidx.browser.trusted.TrustedWebActivityService> cannot be instantiated
04-09 13:16:10.704  4651  4651 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3519)
04-09 13:16:10.704  4651  4651 E AndroidRuntime:        at android.app.ActivityThread.access$1300(ActivityThread.java:199)
04-09 13:16:10.704  4651  4651 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666)
04-09 13:16:10.704  4651  4651 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
04-09 13:16:10.704  4651  4651 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
04-09 13:16:10.704  4651  4651 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6669)
04-09 13:16:10.704  4651  4651 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-09 13:16:10.704  4651  4651 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-09 13:16:10.704  4651  4651 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
04-09 13:16:10.704  4651  4651 E AndroidRuntime: Caused by: java.lang.InstantiationException: java.lang.Class<androidx.browser.trusted.TrustedWebActivityService> cannot be instantiated
04-09 13:16:10.704  4651  4651 E AndroidRuntime:        at java.lang.Class.newInstance(Native Method)
04-09 13:16:10.704  4651  4651 E AndroidRuntime:        at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:103)
04-09 13:16:10.704  4651  4651 E AndroidRuntime:        at androidx.core.app.CoreComponentFactory.instantiateService(Unknown Source:0)
04-09 13:16:10.704  4651  4651 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3514)
04-09 13:16:10.704  4651  4651 E AndroidRuntime:        ... 8 more
04-09 13:16:11.870  4823  4823 D AndroidRuntime: Shutting down VM
```

Is anyone having this problem?

**Comment by andreban** [comment]
Hi @rod-stuchi, would you mind posting your `build.gradle` and `AndroidManifest.xml`? Also,  we do recommend bootstrapping an app with Bubblewrap (https://github.com/GoogleChromeLabs/bubblewrap) instead of cloning svgomg-twa nowadays. If you are not adding any custom code, it also builds the project (you still need a JDK and Android CLI tools, but not Android Studio)

**Comment by rod-stuchi** [comment]
Hi @andreban thanks!

I'm doing more tests to confirm, but apparently it's solved by this.

```
// implementation 'com.google.androidbrowserhelper:androidbrowserhelper:1.2.0'
implementation 'androidx.browser:browser:1.0.0'
implementation 'com.github.GoogleChrome:android-browser-helper:ff8dfc4ed3d4133aacc837673c88d090d3628ec8'
```

⚠ This problem started just after I setup the `.well-known/assetlinks.json` to hide the address bar

The files you requested
[files.tar.gz](https://github.com/GoogleChromeLabs/svgomg-twa/files/4457562/files.tar.gz)

**Comment by andreban** [comment]
So, the error was caused by this:

```xml
        <service
             android:name="androidx.browser.trusted.TrustedWebActivityService"
             android:enabled="@bool/enableNotification"
             android:exported="@bool/enableNotification">

             <intent-filter>
                 <action android:name="android.support.customtabs.trusted.TRUSTED_WEB_ACTIVITY_SERVICE"/>
                 <category android:name="android.intent.category.DEFAULT"/>
            </intent-filter>
         </service>
```
Check how it should like in the sample: https://github.com/GoogleChromeLabs/svgomg-twa/blob/master/app/src/main/AndroidManifest.xml#L93-L102

Summarising, where it reads `android:name="androidx.browser.trusted.TrustedWebActivityService"` it should be `android:name="com.google.androidbrowserhelper.trusted.DelegationService"`

**Don't use `com.github.GoogleChrome:android-browser-helper`**. The correct way to use is via the proper library releases. The particular version you pointed to is from **September 2019** and **doesn't contain many bufixes and latest features**. 

If the project was started on the old version of the library, there's a migration guide here:
https://developers.google.com/web/android/trusted-web-activity/android-browser-helper-migration

**Comment by rod-stuchi** [comment]
@andreban thank you so much! 
You saved the day 🙏
