### ISSUE TITLE
by upgrading library to  7a2c1374a3 ..manifest show conflicts as unresolved class..

### ISSUE THREAD

**Issue by abhishek8506** [GoogleChromeLabs/svgomg-twa#39]
i simply download project and run at first time if u not open manifest it run perfectly ,,then after u open manifest its show error .. Any one should help me..

**Comment by jahooma** [comment]
Same problem here, I think. I switched to version d08e93fce3 and it works.

**Comment by jahooma** [comment]
Actually I might have a different error. 

When I upgrade to com.github.GoogleChrome.custom-tabs-client:customtabs:91b4a1270b, I get the logcat error below.

Maybe my other dependencies are of the wrong version?

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: live.throne, PID: 10018
    java.lang.IllegalAccessError: Method 'android.os.Bundle android.support.customtabs.CustomTabColorSchemeParams.toBundle()' is inaccessible to class 'androidx.browser.customtabs.CustomTabsIntent$Builder' (declaration of 'androidx.browser.customtabs.CustomTabsIntent$Builder' appears in /data/app/live.throne-EyZgOedElgYeooVfSZTF5w==/base.apk)
        at androidx.browser.customtabs.CustomTabsIntent$Builder.build(CustomTabsIntent.java:746)
        at android.support.customtabs.trusted.TrustedWebActivityIntentBuilder.build(TrustedWebActivityIntentBuilder.java:141)
        at android.support.customtabs.trusted.TwaLauncher.launchWhenSplashScreenReady(TwaLauncher.java:185)
        at android.support.customtabs.trusted.TwaLauncher.launchWhenSessionEstablished(TwaLauncher.java:178)
        at android.support.customtabs.trusted.TwaLauncher.lambda$launchTwa$0$TwaLauncher(TwaLauncher.java:153)
        at android.support.customtabs.trusted.-$$Lambda$TwaLauncher$f0OnWewitepqy4BDJ8g8HMz1oZ8.run(Unknown Source:8)
        at android.support.customtabs.trusted.TwaLauncher$TwaCustomTabsServiceConnection.onCustomTabsServiceConnected(TwaLauncher.java:222)
        at androidx.browser.customtabs.CustomTabsServiceConnection.onServiceConnected(CustomTabsServiceConnection.java:44)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1730)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1762)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by jahooma** [comment]
So I did a binary search through the versions of custom-tabs-client I saw on their github page. It turns out that this commit is causing my error: https://github.com/GoogleChrome/custom-tabs-client/commit/59af5454e3add89ad3786e14fd08e9cdc350bef7

Not sure what to do about that. In the meantime, if I use the version right before this from May 15th ('com.github.GoogleChrome.custom-tabs-client:customtabs:3e2f06a3b3'), I can use the splash screen loading feature, which was all I wanted for now. Maybe if I try again in a few months it will all magically be working?

**Comment by tobiasharle** [comment]
@jahooma I am experiencing the same problem so I reported an [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1001491)

**Comment by andreban** [comment]
@jahooma @tobiasharle Are you using other libraries with the project? If not, it may be possible to disable jetifier (`android.enableJetifier=false` in `gradle.properties`) and then ensuring that you are not using other libraries in the apps `build.gradle`. 

The [android-browser-helper](https://github.com/GoogleChrome/android-browser-helper) depends on an alpha version of androidx.browser and should go stable once that library goes stable as well.

**Comment by tobiasharle** [comment]
@andreban At the time of writing I wan't aware of android-browser-helper. Using that instead of custom-tabs-client solved the issue for me.

**Comment by andreban** [comment]
Closing the issue, as it's a Support Library issue and being tracked on Chromium bugs here: https://bugs.chromium.org/p/chromium/issues/detail?id=983378
